// source: messages.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.vdcapi.Message');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.vdcapi.GenericResponse');
goog.require('proto.vdcapi.vdc_ResponseGetProperty');
goog.require('proto.vdcapi.vdc_ResponseHello');
goog.require('proto.vdcapi.vdc_SendAnnounceDevice');
goog.require('proto.vdcapi.vdc_SendAnnounceVdc');
goog.require('proto.vdcapi.vdc_SendIdentify');
goog.require('proto.vdcapi.vdc_SendPong');
goog.require('proto.vdcapi.vdc_SendPushNotification');
goog.require('proto.vdcapi.vdc_SendVanish');
goog.require('proto.vdcapi.vdsm_NotificationCallMinScene');
goog.require('proto.vdcapi.vdsm_NotificationCallScene');
goog.require('proto.vdcapi.vdsm_NotificationDimChannel');
goog.require('proto.vdcapi.vdsm_NotificationIdentify');
goog.require('proto.vdcapi.vdsm_NotificationSaveScene');
goog.require('proto.vdcapi.vdsm_NotificationSetControlValue');
goog.require('proto.vdcapi.vdsm_NotificationSetLocalPrio');
goog.require('proto.vdcapi.vdsm_NotificationSetOutputChannelValue');
goog.require('proto.vdcapi.vdsm_NotificationUndoScene');
goog.require('proto.vdcapi.vdsm_RequestGenericRequest');
goog.require('proto.vdcapi.vdsm_RequestGetProperty');
goog.require('proto.vdcapi.vdsm_RequestHello');
goog.require('proto.vdcapi.vdsm_RequestSetProperty');
goog.require('proto.vdcapi.vdsm_SendBye');
goog.require('proto.vdcapi.vdsm_SendPing');
goog.require('proto.vdcapi.vdsm_SendRemove');

goog.forwardDeclare('proto.vdcapi.Type');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vdcapi.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vdcapi.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vdcapi.Message.displayName = 'proto.vdcapi.Message';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vdcapi.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.vdcapi.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vdcapi.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 1),
    messageId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    genericResponse: (f = msg.getGenericResponse()) && proto.vdcapi.GenericResponse.toObject(includeInstance, f),
    vdsmRequestHello: (f = msg.getVdsmRequestHello()) && proto.vdcapi.vdsm_RequestHello.toObject(includeInstance, f),
    vdcResponseHello: (f = msg.getVdcResponseHello()) && proto.vdcapi.vdc_ResponseHello.toObject(includeInstance, f),
    vdsmRequestGetProperty: (f = msg.getVdsmRequestGetProperty()) && proto.vdcapi.vdsm_RequestGetProperty.toObject(includeInstance, f),
    vdcResponseGetProperty: (f = msg.getVdcResponseGetProperty()) && proto.vdcapi.vdc_ResponseGetProperty.toObject(includeInstance, f),
    vdsmRequestSetProperty: (f = msg.getVdsmRequestSetProperty()) && proto.vdcapi.vdsm_RequestSetProperty.toObject(includeInstance, f),
    vdsmRequestGenericRequest: (f = msg.getVdsmRequestGenericRequest()) && proto.vdcapi.vdsm_RequestGenericRequest.toObject(includeInstance, f),
    vdsmSendPing: (f = msg.getVdsmSendPing()) && proto.vdcapi.vdsm_SendPing.toObject(includeInstance, f),
    vdcSendPong: (f = msg.getVdcSendPong()) && proto.vdcapi.vdc_SendPong.toObject(includeInstance, f),
    vdcSendAnnounceDevice: (f = msg.getVdcSendAnnounceDevice()) && proto.vdcapi.vdc_SendAnnounceDevice.toObject(includeInstance, f),
    vdcSendVanish: (f = msg.getVdcSendVanish()) && proto.vdcapi.vdc_SendVanish.toObject(includeInstance, f),
    vdcSendPushNotification: (f = msg.getVdcSendPushNotification()) && proto.vdcapi.vdc_SendPushNotification.toObject(includeInstance, f),
    vdsmSendRemove: (f = msg.getVdsmSendRemove()) && proto.vdcapi.vdsm_SendRemove.toObject(includeInstance, f),
    vdsmSendBye: (f = msg.getVdsmSendBye()) && proto.vdcapi.vdsm_SendBye.toObject(includeInstance, f),
    vdcSendAnnounceVdc: (f = msg.getVdcSendAnnounceVdc()) && proto.vdcapi.vdc_SendAnnounceVdc.toObject(includeInstance, f),
    vdsmSendCallScene: (f = msg.getVdsmSendCallScene()) && proto.vdcapi.vdsm_NotificationCallScene.toObject(includeInstance, f),
    vdsmSendSaveScene: (f = msg.getVdsmSendSaveScene()) && proto.vdcapi.vdsm_NotificationSaveScene.toObject(includeInstance, f),
    vdsmSendUndoScene: (f = msg.getVdsmSendUndoScene()) && proto.vdcapi.vdsm_NotificationUndoScene.toObject(includeInstance, f),
    vdsmSendSetLocalPrio: (f = msg.getVdsmSendSetLocalPrio()) && proto.vdcapi.vdsm_NotificationSetLocalPrio.toObject(includeInstance, f),
    vdsmSendCallMinScene: (f = msg.getVdsmSendCallMinScene()) && proto.vdcapi.vdsm_NotificationCallMinScene.toObject(includeInstance, f),
    vdsmSendIdentify: (f = msg.getVdsmSendIdentify()) && proto.vdcapi.vdsm_NotificationIdentify.toObject(includeInstance, f),
    vdsmSendSetControlValue: (f = msg.getVdsmSendSetControlValue()) && proto.vdcapi.vdsm_NotificationSetControlValue.toObject(includeInstance, f),
    vdsmSendDimChannel: (f = msg.getVdsmSendDimChannel()) && proto.vdcapi.vdsm_NotificationDimChannel.toObject(includeInstance, f),
    vdsmSendOutputChannelValue: (f = msg.getVdsmSendOutputChannelValue()) && proto.vdcapi.vdsm_NotificationSetOutputChannelValue.toObject(includeInstance, f),
    vdcSendIdentify: (f = msg.getVdcSendIdentify()) && proto.vdcapi.vdc_SendIdentify.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vdcapi.Message}
 */
proto.vdcapi.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vdcapi.Message;
  return proto.vdcapi.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vdcapi.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vdcapi.Message}
 */
proto.vdcapi.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.vdcapi.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMessageId(value);
      break;
    case 3:
      var value = new proto.vdcapi.GenericResponse;
      reader.readMessage(value,proto.vdcapi.GenericResponse.deserializeBinaryFromReader);
      msg.setGenericResponse(value);
      break;
    case 100:
      var value = new proto.vdcapi.vdsm_RequestHello;
      reader.readMessage(value,proto.vdcapi.vdsm_RequestHello.deserializeBinaryFromReader);
      msg.setVdsmRequestHello(value);
      break;
    case 101:
      var value = new proto.vdcapi.vdc_ResponseHello;
      reader.readMessage(value,proto.vdcapi.vdc_ResponseHello.deserializeBinaryFromReader);
      msg.setVdcResponseHello(value);
      break;
    case 102:
      var value = new proto.vdcapi.vdsm_RequestGetProperty;
      reader.readMessage(value,proto.vdcapi.vdsm_RequestGetProperty.deserializeBinaryFromReader);
      msg.setVdsmRequestGetProperty(value);
      break;
    case 103:
      var value = new proto.vdcapi.vdc_ResponseGetProperty;
      reader.readMessage(value,proto.vdcapi.vdc_ResponseGetProperty.deserializeBinaryFromReader);
      msg.setVdcResponseGetProperty(value);
      break;
    case 104:
      var value = new proto.vdcapi.vdsm_RequestSetProperty;
      reader.readMessage(value,proto.vdcapi.vdsm_RequestSetProperty.deserializeBinaryFromReader);
      msg.setVdsmRequestSetProperty(value);
      break;
    case 123:
      var value = new proto.vdcapi.vdsm_RequestGenericRequest;
      reader.readMessage(value,proto.vdcapi.vdsm_RequestGenericRequest.deserializeBinaryFromReader);
      msg.setVdsmRequestGenericRequest(value);
      break;
    case 105:
      var value = new proto.vdcapi.vdsm_SendPing;
      reader.readMessage(value,proto.vdcapi.vdsm_SendPing.deserializeBinaryFromReader);
      msg.setVdsmSendPing(value);
      break;
    case 106:
      var value = new proto.vdcapi.vdc_SendPong;
      reader.readMessage(value,proto.vdcapi.vdc_SendPong.deserializeBinaryFromReader);
      msg.setVdcSendPong(value);
      break;
    case 107:
      var value = new proto.vdcapi.vdc_SendAnnounceDevice;
      reader.readMessage(value,proto.vdcapi.vdc_SendAnnounceDevice.deserializeBinaryFromReader);
      msg.setVdcSendAnnounceDevice(value);
      break;
    case 108:
      var value = new proto.vdcapi.vdc_SendVanish;
      reader.readMessage(value,proto.vdcapi.vdc_SendVanish.deserializeBinaryFromReader);
      msg.setVdcSendVanish(value);
      break;
    case 109:
      var value = new proto.vdcapi.vdc_SendPushNotification;
      reader.readMessage(value,proto.vdcapi.vdc_SendPushNotification.deserializeBinaryFromReader);
      msg.setVdcSendPushNotification(value);
      break;
    case 110:
      var value = new proto.vdcapi.vdsm_SendRemove;
      reader.readMessage(value,proto.vdcapi.vdsm_SendRemove.deserializeBinaryFromReader);
      msg.setVdsmSendRemove(value);
      break;
    case 111:
      var value = new proto.vdcapi.vdsm_SendBye;
      reader.readMessage(value,proto.vdcapi.vdsm_SendBye.deserializeBinaryFromReader);
      msg.setVdsmSendBye(value);
      break;
    case 120:
      var value = new proto.vdcapi.vdc_SendAnnounceVdc;
      reader.readMessage(value,proto.vdcapi.vdc_SendAnnounceVdc.deserializeBinaryFromReader);
      msg.setVdcSendAnnounceVdc(value);
      break;
    case 112:
      var value = new proto.vdcapi.vdsm_NotificationCallScene;
      reader.readMessage(value,proto.vdcapi.vdsm_NotificationCallScene.deserializeBinaryFromReader);
      msg.setVdsmSendCallScene(value);
      break;
    case 113:
      var value = new proto.vdcapi.vdsm_NotificationSaveScene;
      reader.readMessage(value,proto.vdcapi.vdsm_NotificationSaveScene.deserializeBinaryFromReader);
      msg.setVdsmSendSaveScene(value);
      break;
    case 114:
      var value = new proto.vdcapi.vdsm_NotificationUndoScene;
      reader.readMessage(value,proto.vdcapi.vdsm_NotificationUndoScene.deserializeBinaryFromReader);
      msg.setVdsmSendUndoScene(value);
      break;
    case 115:
      var value = new proto.vdcapi.vdsm_NotificationSetLocalPrio;
      reader.readMessage(value,proto.vdcapi.vdsm_NotificationSetLocalPrio.deserializeBinaryFromReader);
      msg.setVdsmSendSetLocalPrio(value);
      break;
    case 116:
      var value = new proto.vdcapi.vdsm_NotificationCallMinScene;
      reader.readMessage(value,proto.vdcapi.vdsm_NotificationCallMinScene.deserializeBinaryFromReader);
      msg.setVdsmSendCallMinScene(value);
      break;
    case 117:
      var value = new proto.vdcapi.vdsm_NotificationIdentify;
      reader.readMessage(value,proto.vdcapi.vdsm_NotificationIdentify.deserializeBinaryFromReader);
      msg.setVdsmSendIdentify(value);
      break;
    case 118:
      var value = new proto.vdcapi.vdsm_NotificationSetControlValue;
      reader.readMessage(value,proto.vdcapi.vdsm_NotificationSetControlValue.deserializeBinaryFromReader);
      msg.setVdsmSendSetControlValue(value);
      break;
    case 121:
      var value = new proto.vdcapi.vdsm_NotificationDimChannel;
      reader.readMessage(value,proto.vdcapi.vdsm_NotificationDimChannel.deserializeBinaryFromReader);
      msg.setVdsmSendDimChannel(value);
      break;
    case 122:
      var value = new proto.vdcapi.vdsm_NotificationSetOutputChannelValue;
      reader.readMessage(value,proto.vdcapi.vdsm_NotificationSetOutputChannelValue.deserializeBinaryFromReader);
      msg.setVdsmSendOutputChannelValue(value);
      break;
    case 119:
      var value = new proto.vdcapi.vdc_SendIdentify;
      reader.readMessage(value,proto.vdcapi.vdc_SendIdentify.deserializeBinaryFromReader);
      msg.setVdcSendIdentify(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vdcapi.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vdcapi.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vdcapi.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.vdcapi.Type} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getGenericResponse();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.vdcapi.GenericResponse.serializeBinaryToWriter
    );
  }
  f = message.getVdsmRequestHello();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.vdcapi.vdsm_RequestHello.serializeBinaryToWriter
    );
  }
  f = message.getVdcResponseHello();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      proto.vdcapi.vdc_ResponseHello.serializeBinaryToWriter
    );
  }
  f = message.getVdsmRequestGetProperty();
  if (f != null) {
    writer.writeMessage(
      102,
      f,
      proto.vdcapi.vdsm_RequestGetProperty.serializeBinaryToWriter
    );
  }
  f = message.getVdcResponseGetProperty();
  if (f != null) {
    writer.writeMessage(
      103,
      f,
      proto.vdcapi.vdc_ResponseGetProperty.serializeBinaryToWriter
    );
  }
  f = message.getVdsmRequestSetProperty();
  if (f != null) {
    writer.writeMessage(
      104,
      f,
      proto.vdcapi.vdsm_RequestSetProperty.serializeBinaryToWriter
    );
  }
  f = message.getVdsmRequestGenericRequest();
  if (f != null) {
    writer.writeMessage(
      123,
      f,
      proto.vdcapi.vdsm_RequestGenericRequest.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendPing();
  if (f != null) {
    writer.writeMessage(
      105,
      f,
      proto.vdcapi.vdsm_SendPing.serializeBinaryToWriter
    );
  }
  f = message.getVdcSendPong();
  if (f != null) {
    writer.writeMessage(
      106,
      f,
      proto.vdcapi.vdc_SendPong.serializeBinaryToWriter
    );
  }
  f = message.getVdcSendAnnounceDevice();
  if (f != null) {
    writer.writeMessage(
      107,
      f,
      proto.vdcapi.vdc_SendAnnounceDevice.serializeBinaryToWriter
    );
  }
  f = message.getVdcSendVanish();
  if (f != null) {
    writer.writeMessage(
      108,
      f,
      proto.vdcapi.vdc_SendVanish.serializeBinaryToWriter
    );
  }
  f = message.getVdcSendPushNotification();
  if (f != null) {
    writer.writeMessage(
      109,
      f,
      proto.vdcapi.vdc_SendPushNotification.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendRemove();
  if (f != null) {
    writer.writeMessage(
      110,
      f,
      proto.vdcapi.vdsm_SendRemove.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendBye();
  if (f != null) {
    writer.writeMessage(
      111,
      f,
      proto.vdcapi.vdsm_SendBye.serializeBinaryToWriter
    );
  }
  f = message.getVdcSendAnnounceVdc();
  if (f != null) {
    writer.writeMessage(
      120,
      f,
      proto.vdcapi.vdc_SendAnnounceVdc.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendCallScene();
  if (f != null) {
    writer.writeMessage(
      112,
      f,
      proto.vdcapi.vdsm_NotificationCallScene.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendSaveScene();
  if (f != null) {
    writer.writeMessage(
      113,
      f,
      proto.vdcapi.vdsm_NotificationSaveScene.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendUndoScene();
  if (f != null) {
    writer.writeMessage(
      114,
      f,
      proto.vdcapi.vdsm_NotificationUndoScene.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendSetLocalPrio();
  if (f != null) {
    writer.writeMessage(
      115,
      f,
      proto.vdcapi.vdsm_NotificationSetLocalPrio.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendCallMinScene();
  if (f != null) {
    writer.writeMessage(
      116,
      f,
      proto.vdcapi.vdsm_NotificationCallMinScene.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendIdentify();
  if (f != null) {
    writer.writeMessage(
      117,
      f,
      proto.vdcapi.vdsm_NotificationIdentify.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendSetControlValue();
  if (f != null) {
    writer.writeMessage(
      118,
      f,
      proto.vdcapi.vdsm_NotificationSetControlValue.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendDimChannel();
  if (f != null) {
    writer.writeMessage(
      121,
      f,
      proto.vdcapi.vdsm_NotificationDimChannel.serializeBinaryToWriter
    );
  }
  f = message.getVdsmSendOutputChannelValue();
  if (f != null) {
    writer.writeMessage(
      122,
      f,
      proto.vdcapi.vdsm_NotificationSetOutputChannelValue.serializeBinaryToWriter
    );
  }
  f = message.getVdcSendIdentify();
  if (f != null) {
    writer.writeMessage(
      119,
      f,
      proto.vdcapi.vdc_SendIdentify.serializeBinaryToWriter
    );
  }
};


/**
 * required Type type = 1;
 * @return {!proto.vdcapi.Type}
 */
proto.vdcapi.Message.prototype.getType = function() {
  return /** @type {!proto.vdcapi.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 1));
};


/**
 * @param {!proto.vdcapi.Type} value
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.setType = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearType = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 message_id = 2;
 * @return {number}
 */
proto.vdcapi.Message.prototype.getMessageId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.setMessageId = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearMessageId = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasMessageId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GenericResponse generic_response = 3;
 * @return {?proto.vdcapi.GenericResponse}
 */
proto.vdcapi.Message.prototype.getGenericResponse = function() {
  return /** @type{?proto.vdcapi.GenericResponse} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.GenericResponse, 3));
};


/**
 * @param {?proto.vdcapi.GenericResponse|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setGenericResponse = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearGenericResponse = function() {
  return this.setGenericResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasGenericResponse = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional vdsm_RequestHello vdsm_request_hello = 100;
 * @return {?proto.vdcapi.vdsm_RequestHello}
 */
proto.vdcapi.Message.prototype.getVdsmRequestHello = function() {
  return /** @type{?proto.vdcapi.vdsm_RequestHello} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_RequestHello, 100));
};


/**
 * @param {?proto.vdcapi.vdsm_RequestHello|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmRequestHello = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmRequestHello = function() {
  return this.setVdsmRequestHello(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmRequestHello = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional vdc_ResponseHello vdc_response_hello = 101;
 * @return {?proto.vdcapi.vdc_ResponseHello}
 */
proto.vdcapi.Message.prototype.getVdcResponseHello = function() {
  return /** @type{?proto.vdcapi.vdc_ResponseHello} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdc_ResponseHello, 101));
};


/**
 * @param {?proto.vdcapi.vdc_ResponseHello|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdcResponseHello = function(value) {
  return jspb.Message.setWrapperField(this, 101, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdcResponseHello = function() {
  return this.setVdcResponseHello(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdcResponseHello = function() {
  return jspb.Message.getField(this, 101) != null;
};


/**
 * optional vdsm_RequestGetProperty vdsm_request_get_property = 102;
 * @return {?proto.vdcapi.vdsm_RequestGetProperty}
 */
proto.vdcapi.Message.prototype.getVdsmRequestGetProperty = function() {
  return /** @type{?proto.vdcapi.vdsm_RequestGetProperty} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_RequestGetProperty, 102));
};


/**
 * @param {?proto.vdcapi.vdsm_RequestGetProperty|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmRequestGetProperty = function(value) {
  return jspb.Message.setWrapperField(this, 102, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmRequestGetProperty = function() {
  return this.setVdsmRequestGetProperty(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmRequestGetProperty = function() {
  return jspb.Message.getField(this, 102) != null;
};


/**
 * optional vdc_ResponseGetProperty vdc_response_get_property = 103;
 * @return {?proto.vdcapi.vdc_ResponseGetProperty}
 */
proto.vdcapi.Message.prototype.getVdcResponseGetProperty = function() {
  return /** @type{?proto.vdcapi.vdc_ResponseGetProperty} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdc_ResponseGetProperty, 103));
};


/**
 * @param {?proto.vdcapi.vdc_ResponseGetProperty|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdcResponseGetProperty = function(value) {
  return jspb.Message.setWrapperField(this, 103, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdcResponseGetProperty = function() {
  return this.setVdcResponseGetProperty(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdcResponseGetProperty = function() {
  return jspb.Message.getField(this, 103) != null;
};


/**
 * optional vdsm_RequestSetProperty vdsm_request_set_property = 104;
 * @return {?proto.vdcapi.vdsm_RequestSetProperty}
 */
proto.vdcapi.Message.prototype.getVdsmRequestSetProperty = function() {
  return /** @type{?proto.vdcapi.vdsm_RequestSetProperty} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_RequestSetProperty, 104));
};


/**
 * @param {?proto.vdcapi.vdsm_RequestSetProperty|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmRequestSetProperty = function(value) {
  return jspb.Message.setWrapperField(this, 104, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmRequestSetProperty = function() {
  return this.setVdsmRequestSetProperty(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmRequestSetProperty = function() {
  return jspb.Message.getField(this, 104) != null;
};


/**
 * optional vdsm_RequestGenericRequest vdsm_request_generic_request = 123;
 * @return {?proto.vdcapi.vdsm_RequestGenericRequest}
 */
proto.vdcapi.Message.prototype.getVdsmRequestGenericRequest = function() {
  return /** @type{?proto.vdcapi.vdsm_RequestGenericRequest} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_RequestGenericRequest, 123));
};


/**
 * @param {?proto.vdcapi.vdsm_RequestGenericRequest|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmRequestGenericRequest = function(value) {
  return jspb.Message.setWrapperField(this, 123, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmRequestGenericRequest = function() {
  return this.setVdsmRequestGenericRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmRequestGenericRequest = function() {
  return jspb.Message.getField(this, 123) != null;
};


/**
 * optional vdsm_SendPing vdsm_send_ping = 105;
 * @return {?proto.vdcapi.vdsm_SendPing}
 */
proto.vdcapi.Message.prototype.getVdsmSendPing = function() {
  return /** @type{?proto.vdcapi.vdsm_SendPing} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_SendPing, 105));
};


/**
 * @param {?proto.vdcapi.vdsm_SendPing|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendPing = function(value) {
  return jspb.Message.setWrapperField(this, 105, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendPing = function() {
  return this.setVdsmSendPing(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendPing = function() {
  return jspb.Message.getField(this, 105) != null;
};


/**
 * optional vdc_SendPong vdc_send_pong = 106;
 * @return {?proto.vdcapi.vdc_SendPong}
 */
proto.vdcapi.Message.prototype.getVdcSendPong = function() {
  return /** @type{?proto.vdcapi.vdc_SendPong} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdc_SendPong, 106));
};


/**
 * @param {?proto.vdcapi.vdc_SendPong|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdcSendPong = function(value) {
  return jspb.Message.setWrapperField(this, 106, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdcSendPong = function() {
  return this.setVdcSendPong(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdcSendPong = function() {
  return jspb.Message.getField(this, 106) != null;
};


/**
 * optional vdc_SendAnnounceDevice vdc_send_announce_device = 107;
 * @return {?proto.vdcapi.vdc_SendAnnounceDevice}
 */
proto.vdcapi.Message.prototype.getVdcSendAnnounceDevice = function() {
  return /** @type{?proto.vdcapi.vdc_SendAnnounceDevice} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdc_SendAnnounceDevice, 107));
};


/**
 * @param {?proto.vdcapi.vdc_SendAnnounceDevice|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdcSendAnnounceDevice = function(value) {
  return jspb.Message.setWrapperField(this, 107, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdcSendAnnounceDevice = function() {
  return this.setVdcSendAnnounceDevice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdcSendAnnounceDevice = function() {
  return jspb.Message.getField(this, 107) != null;
};


/**
 * optional vdc_SendVanish vdc_send_vanish = 108;
 * @return {?proto.vdcapi.vdc_SendVanish}
 */
proto.vdcapi.Message.prototype.getVdcSendVanish = function() {
  return /** @type{?proto.vdcapi.vdc_SendVanish} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdc_SendVanish, 108));
};


/**
 * @param {?proto.vdcapi.vdc_SendVanish|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdcSendVanish = function(value) {
  return jspb.Message.setWrapperField(this, 108, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdcSendVanish = function() {
  return this.setVdcSendVanish(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdcSendVanish = function() {
  return jspb.Message.getField(this, 108) != null;
};


/**
 * optional vdc_SendPushNotification vdc_send_push_notification = 109;
 * @return {?proto.vdcapi.vdc_SendPushNotification}
 */
proto.vdcapi.Message.prototype.getVdcSendPushNotification = function() {
  return /** @type{?proto.vdcapi.vdc_SendPushNotification} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdc_SendPushNotification, 109));
};


/**
 * @param {?proto.vdcapi.vdc_SendPushNotification|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdcSendPushNotification = function(value) {
  return jspb.Message.setWrapperField(this, 109, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdcSendPushNotification = function() {
  return this.setVdcSendPushNotification(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdcSendPushNotification = function() {
  return jspb.Message.getField(this, 109) != null;
};


/**
 * optional vdsm_SendRemove vdsm_send_remove = 110;
 * @return {?proto.vdcapi.vdsm_SendRemove}
 */
proto.vdcapi.Message.prototype.getVdsmSendRemove = function() {
  return /** @type{?proto.vdcapi.vdsm_SendRemove} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_SendRemove, 110));
};


/**
 * @param {?proto.vdcapi.vdsm_SendRemove|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendRemove = function(value) {
  return jspb.Message.setWrapperField(this, 110, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendRemove = function() {
  return this.setVdsmSendRemove(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendRemove = function() {
  return jspb.Message.getField(this, 110) != null;
};


/**
 * optional vdsm_SendBye vdsm_send_bye = 111;
 * @return {?proto.vdcapi.vdsm_SendBye}
 */
proto.vdcapi.Message.prototype.getVdsmSendBye = function() {
  return /** @type{?proto.vdcapi.vdsm_SendBye} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_SendBye, 111));
};


/**
 * @param {?proto.vdcapi.vdsm_SendBye|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendBye = function(value) {
  return jspb.Message.setWrapperField(this, 111, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendBye = function() {
  return this.setVdsmSendBye(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendBye = function() {
  return jspb.Message.getField(this, 111) != null;
};


/**
 * optional vdc_SendAnnounceVdc vdc_send_announce_vdc = 120;
 * @return {?proto.vdcapi.vdc_SendAnnounceVdc}
 */
proto.vdcapi.Message.prototype.getVdcSendAnnounceVdc = function() {
  return /** @type{?proto.vdcapi.vdc_SendAnnounceVdc} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdc_SendAnnounceVdc, 120));
};


/**
 * @param {?proto.vdcapi.vdc_SendAnnounceVdc|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdcSendAnnounceVdc = function(value) {
  return jspb.Message.setWrapperField(this, 120, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdcSendAnnounceVdc = function() {
  return this.setVdcSendAnnounceVdc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdcSendAnnounceVdc = function() {
  return jspb.Message.getField(this, 120) != null;
};


/**
 * optional vdsm_NotificationCallScene vdsm_send_call_scene = 112;
 * @return {?proto.vdcapi.vdsm_NotificationCallScene}
 */
proto.vdcapi.Message.prototype.getVdsmSendCallScene = function() {
  return /** @type{?proto.vdcapi.vdsm_NotificationCallScene} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_NotificationCallScene, 112));
};


/**
 * @param {?proto.vdcapi.vdsm_NotificationCallScene|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendCallScene = function(value) {
  return jspb.Message.setWrapperField(this, 112, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendCallScene = function() {
  return this.setVdsmSendCallScene(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendCallScene = function() {
  return jspb.Message.getField(this, 112) != null;
};


/**
 * optional vdsm_NotificationSaveScene vdsm_send_save_scene = 113;
 * @return {?proto.vdcapi.vdsm_NotificationSaveScene}
 */
proto.vdcapi.Message.prototype.getVdsmSendSaveScene = function() {
  return /** @type{?proto.vdcapi.vdsm_NotificationSaveScene} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_NotificationSaveScene, 113));
};


/**
 * @param {?proto.vdcapi.vdsm_NotificationSaveScene|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendSaveScene = function(value) {
  return jspb.Message.setWrapperField(this, 113, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendSaveScene = function() {
  return this.setVdsmSendSaveScene(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendSaveScene = function() {
  return jspb.Message.getField(this, 113) != null;
};


/**
 * optional vdsm_NotificationUndoScene vdsm_send_undo_scene = 114;
 * @return {?proto.vdcapi.vdsm_NotificationUndoScene}
 */
proto.vdcapi.Message.prototype.getVdsmSendUndoScene = function() {
  return /** @type{?proto.vdcapi.vdsm_NotificationUndoScene} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_NotificationUndoScene, 114));
};


/**
 * @param {?proto.vdcapi.vdsm_NotificationUndoScene|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendUndoScene = function(value) {
  return jspb.Message.setWrapperField(this, 114, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendUndoScene = function() {
  return this.setVdsmSendUndoScene(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendUndoScene = function() {
  return jspb.Message.getField(this, 114) != null;
};


/**
 * optional vdsm_NotificationSetLocalPrio vdsm_send_set_local_prio = 115;
 * @return {?proto.vdcapi.vdsm_NotificationSetLocalPrio}
 */
proto.vdcapi.Message.prototype.getVdsmSendSetLocalPrio = function() {
  return /** @type{?proto.vdcapi.vdsm_NotificationSetLocalPrio} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_NotificationSetLocalPrio, 115));
};


/**
 * @param {?proto.vdcapi.vdsm_NotificationSetLocalPrio|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendSetLocalPrio = function(value) {
  return jspb.Message.setWrapperField(this, 115, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendSetLocalPrio = function() {
  return this.setVdsmSendSetLocalPrio(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendSetLocalPrio = function() {
  return jspb.Message.getField(this, 115) != null;
};


/**
 * optional vdsm_NotificationCallMinScene vdsm_send_call_min_scene = 116;
 * @return {?proto.vdcapi.vdsm_NotificationCallMinScene}
 */
proto.vdcapi.Message.prototype.getVdsmSendCallMinScene = function() {
  return /** @type{?proto.vdcapi.vdsm_NotificationCallMinScene} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_NotificationCallMinScene, 116));
};


/**
 * @param {?proto.vdcapi.vdsm_NotificationCallMinScene|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendCallMinScene = function(value) {
  return jspb.Message.setWrapperField(this, 116, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendCallMinScene = function() {
  return this.setVdsmSendCallMinScene(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendCallMinScene = function() {
  return jspb.Message.getField(this, 116) != null;
};


/**
 * optional vdsm_NotificationIdentify vdsm_send_identify = 117;
 * @return {?proto.vdcapi.vdsm_NotificationIdentify}
 */
proto.vdcapi.Message.prototype.getVdsmSendIdentify = function() {
  return /** @type{?proto.vdcapi.vdsm_NotificationIdentify} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_NotificationIdentify, 117));
};


/**
 * @param {?proto.vdcapi.vdsm_NotificationIdentify|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendIdentify = function(value) {
  return jspb.Message.setWrapperField(this, 117, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendIdentify = function() {
  return this.setVdsmSendIdentify(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendIdentify = function() {
  return jspb.Message.getField(this, 117) != null;
};


/**
 * optional vdsm_NotificationSetControlValue vdsm_send_set_control_value = 118;
 * @return {?proto.vdcapi.vdsm_NotificationSetControlValue}
 */
proto.vdcapi.Message.prototype.getVdsmSendSetControlValue = function() {
  return /** @type{?proto.vdcapi.vdsm_NotificationSetControlValue} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_NotificationSetControlValue, 118));
};


/**
 * @param {?proto.vdcapi.vdsm_NotificationSetControlValue|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendSetControlValue = function(value) {
  return jspb.Message.setWrapperField(this, 118, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendSetControlValue = function() {
  return this.setVdsmSendSetControlValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendSetControlValue = function() {
  return jspb.Message.getField(this, 118) != null;
};


/**
 * optional vdsm_NotificationDimChannel vdsm_send_dim_channel = 121;
 * @return {?proto.vdcapi.vdsm_NotificationDimChannel}
 */
proto.vdcapi.Message.prototype.getVdsmSendDimChannel = function() {
  return /** @type{?proto.vdcapi.vdsm_NotificationDimChannel} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_NotificationDimChannel, 121));
};


/**
 * @param {?proto.vdcapi.vdsm_NotificationDimChannel|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendDimChannel = function(value) {
  return jspb.Message.setWrapperField(this, 121, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendDimChannel = function() {
  return this.setVdsmSendDimChannel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendDimChannel = function() {
  return jspb.Message.getField(this, 121) != null;
};


/**
 * optional vdsm_NotificationSetOutputChannelValue vdsm_send_output_channel_value = 122;
 * @return {?proto.vdcapi.vdsm_NotificationSetOutputChannelValue}
 */
proto.vdcapi.Message.prototype.getVdsmSendOutputChannelValue = function() {
  return /** @type{?proto.vdcapi.vdsm_NotificationSetOutputChannelValue} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdsm_NotificationSetOutputChannelValue, 122));
};


/**
 * @param {?proto.vdcapi.vdsm_NotificationSetOutputChannelValue|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdsmSendOutputChannelValue = function(value) {
  return jspb.Message.setWrapperField(this, 122, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdsmSendOutputChannelValue = function() {
  return this.setVdsmSendOutputChannelValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdsmSendOutputChannelValue = function() {
  return jspb.Message.getField(this, 122) != null;
};


/**
 * optional vdc_SendIdentify vdc_send_identify = 119;
 * @return {?proto.vdcapi.vdc_SendIdentify}
 */
proto.vdcapi.Message.prototype.getVdcSendIdentify = function() {
  return /** @type{?proto.vdcapi.vdc_SendIdentify} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.vdc_SendIdentify, 119));
};


/**
 * @param {?proto.vdcapi.vdc_SendIdentify|undefined} value
 * @return {!proto.vdcapi.Message} returns this
*/
proto.vdcapi.Message.prototype.setVdcSendIdentify = function(value) {
  return jspb.Message.setWrapperField(this, 119, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.Message} returns this
 */
proto.vdcapi.Message.prototype.clearVdcSendIdentify = function() {
  return this.setVdcSendIdentify(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.Message.prototype.hasVdcSendIdentify = function() {
  return jspb.Message.getField(this, 119) != null;
};


