// source: vdcapi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.vdcapi.PropertyElement');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.vdcapi.PropertyValue');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vdcapi.PropertyElement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vdcapi.PropertyElement.repeatedFields_, null);
};
goog.inherits(proto.vdcapi.PropertyElement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vdcapi.PropertyElement.displayName = 'proto.vdcapi.PropertyElement';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vdcapi.PropertyElement.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vdcapi.PropertyElement.prototype.toObject = function(opt_includeInstance) {
  return proto.vdcapi.PropertyElement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vdcapi.PropertyElement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.PropertyElement.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    value: (f = msg.getValue()) && proto.vdcapi.PropertyValue.toObject(includeInstance, f),
    elementsList: jspb.Message.toObjectList(msg.getElementsList(),
    proto.vdcapi.PropertyElement.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vdcapi.PropertyElement}
 */
proto.vdcapi.PropertyElement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vdcapi.PropertyElement;
  return proto.vdcapi.PropertyElement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vdcapi.PropertyElement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vdcapi.PropertyElement}
 */
proto.vdcapi.PropertyElement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.vdcapi.PropertyValue;
      reader.readMessage(value,proto.vdcapi.PropertyValue.deserializeBinaryFromReader);
      msg.setValue(value);
      break;
    case 3:
      var value = new proto.vdcapi.PropertyElement;
      reader.readMessage(value,proto.vdcapi.PropertyElement.deserializeBinaryFromReader);
      msg.addElements(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vdcapi.PropertyElement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vdcapi.PropertyElement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vdcapi.PropertyElement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.PropertyElement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.vdcapi.PropertyValue.serializeBinaryToWriter
    );
  }
  f = message.getElementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.vdcapi.PropertyElement.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.vdcapi.PropertyElement.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.vdcapi.PropertyElement} returns this
 */
proto.vdcapi.PropertyElement.prototype.setName = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.PropertyElement} returns this
 */
proto.vdcapi.PropertyElement.prototype.clearName = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.PropertyElement.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PropertyValue value = 2;
 * @return {?proto.vdcapi.PropertyValue}
 */
proto.vdcapi.PropertyElement.prototype.getValue = function() {
  return /** @type{?proto.vdcapi.PropertyValue} */ (
    jspb.Message.getWrapperField(this, proto.vdcapi.PropertyValue, 2));
};


/**
 * @param {?proto.vdcapi.PropertyValue|undefined} value
 * @return {!proto.vdcapi.PropertyElement} returns this
*/
proto.vdcapi.PropertyElement.prototype.setValue = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.vdcapi.PropertyElement} returns this
 */
proto.vdcapi.PropertyElement.prototype.clearValue = function() {
  return this.setValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.PropertyElement.prototype.hasValue = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated PropertyElement elements = 3;
 * @return {!Array<!proto.vdcapi.PropertyElement>}
 */
proto.vdcapi.PropertyElement.prototype.getElementsList = function() {
  return /** @type{!Array<!proto.vdcapi.PropertyElement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.vdcapi.PropertyElement, 3));
};


/**
 * @param {!Array<!proto.vdcapi.PropertyElement>} value
 * @return {!proto.vdcapi.PropertyElement} returns this
*/
proto.vdcapi.PropertyElement.prototype.setElementsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.vdcapi.PropertyElement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.vdcapi.PropertyElement}
 */
proto.vdcapi.PropertyElement.prototype.addElements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.vdcapi.PropertyElement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vdcapi.PropertyElement} returns this
 */
proto.vdcapi.PropertyElement.prototype.clearElementsList = function() {
  return this.setElementsList([]);
};


