// source: vdcapi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.vdcapi.PropertyValue');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vdcapi.PropertyValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vdcapi.PropertyValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vdcapi.PropertyValue.displayName = 'proto.vdcapi.PropertyValue';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vdcapi.PropertyValue.prototype.toObject = function(opt_includeInstance) {
  return proto.vdcapi.PropertyValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vdcapi.PropertyValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.PropertyValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    vBool: (f = jspb.Message.getBooleanField(msg, 1)) == null ? undefined : f,
    vUint64: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    vInt64: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    vDouble: (f = jspb.Message.getOptionalFloatingPointField(msg, 4)) == null ? undefined : f,
    vString: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    vBytes: msg.getVBytes_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vdcapi.PropertyValue}
 */
proto.vdcapi.PropertyValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vdcapi.PropertyValue;
  return proto.vdcapi.PropertyValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vdcapi.PropertyValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vdcapi.PropertyValue}
 */
proto.vdcapi.PropertyValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setVBool(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setVUint64(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setVInt64(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setVDouble(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setVString(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setVBytes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vdcapi.PropertyValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vdcapi.PropertyValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vdcapi.PropertyValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.PropertyValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBytes(
      6,
      f
    );
  }
};


/**
 * optional bool v_bool = 1;
 * @return {boolean}
 */
proto.vdcapi.PropertyValue.prototype.getVBool = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.setVBool = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.clearVBool = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.PropertyValue.prototype.hasVBool = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 v_uint64 = 2;
 * @return {number}
 */
proto.vdcapi.PropertyValue.prototype.getVUint64 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.setVUint64 = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.clearVUint64 = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.PropertyValue.prototype.hasVUint64 = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 v_int64 = 3;
 * @return {number}
 */
proto.vdcapi.PropertyValue.prototype.getVInt64 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.setVInt64 = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.clearVInt64 = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.PropertyValue.prototype.hasVInt64 = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double v_double = 4;
 * @return {number}
 */
proto.vdcapi.PropertyValue.prototype.getVDouble = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.setVDouble = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.clearVDouble = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.PropertyValue.prototype.hasVDouble = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string v_string = 5;
 * @return {string}
 */
proto.vdcapi.PropertyValue.prototype.getVString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.setVString = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.clearVString = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.PropertyValue.prototype.hasVString = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bytes v_bytes = 6;
 * @return {string}
 */
proto.vdcapi.PropertyValue.prototype.getVBytes = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes v_bytes = 6;
 * This is a type-conversion wrapper around `getVBytes()`
 * @return {string}
 */
proto.vdcapi.PropertyValue.prototype.getVBytes_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getVBytes()));
};


/**
 * optional bytes v_bytes = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getVBytes()`
 * @return {!Uint8Array}
 */
proto.vdcapi.PropertyValue.prototype.getVBytes_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getVBytes()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.setVBytes = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.PropertyValue} returns this
 */
proto.vdcapi.PropertyValue.prototype.clearVBytes = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.PropertyValue.prototype.hasVBytes = function() {
  return jspb.Message.getField(this, 6) != null;
};


