// source: messages.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.vdcapi.Type');

/**
 * @enum {number}
 */
proto.vdcapi.Type = {
  GENERIC_RESPONSE: 1,
  VDSM_REQUEST_HELLO: 2,
  VDC_RESPONSE_HELLO: 3,
  VDSM_REQUEST_GET_PROPERTY: 4,
  VDC_RESPONSE_GET_PROPERTY: 5,
  VDSM_REQUEST_SET_PROPERTY: 6,
  VDSM_REQUEST_GENERIC_REQUEST: 26,
  VDSM_SEND_PING: 8,
  VDC_SEND_PONG: 9,
  VDC_SEND_ANNOUNCE_DEVICE: 10,
  VDC_SEND_VANISH: 11,
  VDC_SEND_PUSH_NOTIFICATION: 12,
  VDSM_SEND_REMOVE: 13,
  VDSM_SEND_BYE: 14,
  VDC_SEND_ANNOUNCE_VDC: 23,
  VDSM_NOTIFICATION_CALL_SCENE: 15,
  VDSM_NOTIFICATION_SAVE_SCENE: 16,
  VDSM_NOTIFICATION_UNDO_SCENE: 17,
  VDSM_NOTIFICATION_SET_LOCAL_PRIO: 18,
  VDSM_NOTIFICATION_CALL_MIN_SCENE: 19,
  VDSM_NOTIFICATION_IDENTIFY: 20,
  VDSM_NOTIFICATION_SET_CONTROL_VALUE: 21,
  VDSM_NOTIFICATION_DIM_CHANNEL: 24,
  VDSM_NOTIFICATION_SET_OUTPUT_CHANNEL_VALUE: 25,
  VDC_SEND_IDENTIFY: 22
};

