// source: vdcapi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.vdcapi.vdc_SendPushNotification');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.vdcapi.PropertyElement');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vdcapi.vdc_SendPushNotification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vdcapi.vdc_SendPushNotification.repeatedFields_, null);
};
goog.inherits(proto.vdcapi.vdc_SendPushNotification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vdcapi.vdc_SendPushNotification.displayName = 'proto.vdcapi.vdc_SendPushNotification';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vdcapi.vdc_SendPushNotification.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vdcapi.vdc_SendPushNotification.prototype.toObject = function(opt_includeInstance) {
  return proto.vdcapi.vdc_SendPushNotification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vdcapi.vdc_SendPushNotification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.vdc_SendPushNotification.toObject = function(includeInstance, msg) {
  var f, obj = {
    dsuid: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    changedpropertiesList: jspb.Message.toObjectList(msg.getChangedpropertiesList(),
    proto.vdcapi.PropertyElement.toObject, includeInstance),
    deviceeventsList: jspb.Message.toObjectList(msg.getDeviceeventsList(),
    proto.vdcapi.PropertyElement.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vdcapi.vdc_SendPushNotification}
 */
proto.vdcapi.vdc_SendPushNotification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vdcapi.vdc_SendPushNotification;
  return proto.vdcapi.vdc_SendPushNotification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vdcapi.vdc_SendPushNotification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vdcapi.vdc_SendPushNotification}
 */
proto.vdcapi.vdc_SendPushNotification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDsuid(value);
      break;
    case 2:
      var value = new proto.vdcapi.PropertyElement;
      reader.readMessage(value,proto.vdcapi.PropertyElement.deserializeBinaryFromReader);
      msg.addChangedproperties(value);
      break;
    case 3:
      var value = new proto.vdcapi.PropertyElement;
      reader.readMessage(value,proto.vdcapi.PropertyElement.deserializeBinaryFromReader);
      msg.addDeviceevents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vdcapi.vdc_SendPushNotification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vdcapi.vdc_SendPushNotification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vdcapi.vdc_SendPushNotification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.vdc_SendPushNotification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getChangedpropertiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.vdcapi.PropertyElement.serializeBinaryToWriter
    );
  }
  f = message.getDeviceeventsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.vdcapi.PropertyElement.serializeBinaryToWriter
    );
  }
};


/**
 * optional string dSUID = 1;
 * @return {string}
 */
proto.vdcapi.vdc_SendPushNotification.prototype.getDsuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.vdcapi.vdc_SendPushNotification} returns this
 */
proto.vdcapi.vdc_SendPushNotification.prototype.setDsuid = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.vdc_SendPushNotification} returns this
 */
proto.vdcapi.vdc_SendPushNotification.prototype.clearDsuid = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.vdc_SendPushNotification.prototype.hasDsuid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated PropertyElement changedproperties = 2;
 * @return {!Array<!proto.vdcapi.PropertyElement>}
 */
proto.vdcapi.vdc_SendPushNotification.prototype.getChangedpropertiesList = function() {
  return /** @type{!Array<!proto.vdcapi.PropertyElement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.vdcapi.PropertyElement, 2));
};


/**
 * @param {!Array<!proto.vdcapi.PropertyElement>} value
 * @return {!proto.vdcapi.vdc_SendPushNotification} returns this
*/
proto.vdcapi.vdc_SendPushNotification.prototype.setChangedpropertiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.vdcapi.PropertyElement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.vdcapi.PropertyElement}
 */
proto.vdcapi.vdc_SendPushNotification.prototype.addChangedproperties = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.vdcapi.PropertyElement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vdcapi.vdc_SendPushNotification} returns this
 */
proto.vdcapi.vdc_SendPushNotification.prototype.clearChangedpropertiesList = function() {
  return this.setChangedpropertiesList([]);
};


/**
 * repeated PropertyElement deviceevents = 3;
 * @return {!Array<!proto.vdcapi.PropertyElement>}
 */
proto.vdcapi.vdc_SendPushNotification.prototype.getDeviceeventsList = function() {
  return /** @type{!Array<!proto.vdcapi.PropertyElement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.vdcapi.PropertyElement, 3));
};


/**
 * @param {!Array<!proto.vdcapi.PropertyElement>} value
 * @return {!proto.vdcapi.vdc_SendPushNotification} returns this
*/
proto.vdcapi.vdc_SendPushNotification.prototype.setDeviceeventsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.vdcapi.PropertyElement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.vdcapi.PropertyElement}
 */
proto.vdcapi.vdc_SendPushNotification.prototype.addDeviceevents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.vdcapi.PropertyElement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vdcapi.vdc_SendPushNotification} returns this
 */
proto.vdcapi.vdc_SendPushNotification.prototype.clearDeviceeventsList = function() {
  return this.setDeviceeventsList([]);
};


