// source: vdcapi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.vdcapi.vdsm_RequestGenericRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.vdcapi.PropertyElement');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vdcapi.vdsm_RequestGenericRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vdcapi.vdsm_RequestGenericRequest.repeatedFields_, null);
};
goog.inherits(proto.vdcapi.vdsm_RequestGenericRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vdcapi.vdsm_RequestGenericRequest.displayName = 'proto.vdcapi.vdsm_RequestGenericRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vdcapi.vdsm_RequestGenericRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.vdcapi.vdsm_RequestGenericRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vdcapi.vdsm_RequestGenericRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.vdsm_RequestGenericRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    dsuid: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    methodname: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    paramsList: jspb.Message.toObjectList(msg.getParamsList(),
    proto.vdcapi.PropertyElement.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vdcapi.vdsm_RequestGenericRequest}
 */
proto.vdcapi.vdsm_RequestGenericRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vdcapi.vdsm_RequestGenericRequest;
  return proto.vdcapi.vdsm_RequestGenericRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vdcapi.vdsm_RequestGenericRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vdcapi.vdsm_RequestGenericRequest}
 */
proto.vdcapi.vdsm_RequestGenericRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDsuid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMethodname(value);
      break;
    case 3:
      var value = new proto.vdcapi.PropertyElement;
      reader.readMessage(value,proto.vdcapi.PropertyElement.deserializeBinaryFromReader);
      msg.addParams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vdcapi.vdsm_RequestGenericRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vdcapi.vdsm_RequestGenericRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.vdsm_RequestGenericRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getParamsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.vdcapi.PropertyElement.serializeBinaryToWriter
    );
  }
};


/**
 * optional string dSUID = 1;
 * @return {string}
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.getDsuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.vdcapi.vdsm_RequestGenericRequest} returns this
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.setDsuid = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.vdsm_RequestGenericRequest} returns this
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.clearDsuid = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.hasDsuid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string methodname = 2;
 * @return {string}
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.getMethodname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.vdcapi.vdsm_RequestGenericRequest} returns this
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.setMethodname = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.vdsm_RequestGenericRequest} returns this
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.clearMethodname = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.hasMethodname = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated PropertyElement params = 3;
 * @return {!Array<!proto.vdcapi.PropertyElement>}
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.getParamsList = function() {
  return /** @type{!Array<!proto.vdcapi.PropertyElement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.vdcapi.PropertyElement, 3));
};


/**
 * @param {!Array<!proto.vdcapi.PropertyElement>} value
 * @return {!proto.vdcapi.vdsm_RequestGenericRequest} returns this
*/
proto.vdcapi.vdsm_RequestGenericRequest.prototype.setParamsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.vdcapi.PropertyElement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.vdcapi.PropertyElement}
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.addParams = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.vdcapi.PropertyElement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vdcapi.vdsm_RequestGenericRequest} returns this
 */
proto.vdcapi.vdsm_RequestGenericRequest.prototype.clearParamsList = function() {
  return this.setParamsList([]);
};


