// source: vdcapi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.vdcapi.vdsm_NotificationDimChannel');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vdcapi.vdsm_NotificationDimChannel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.vdcapi.vdsm_NotificationDimChannel.repeatedFields_, null);
};
goog.inherits(proto.vdcapi.vdsm_NotificationDimChannel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vdcapi.vdsm_NotificationDimChannel.displayName = 'proto.vdcapi.vdsm_NotificationDimChannel';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.vdcapi.vdsm_NotificationDimChannel.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.toObject = function(opt_includeInstance) {
  return proto.vdcapi.vdsm_NotificationDimChannel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vdcapi.vdsm_NotificationDimChannel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.vdsm_NotificationDimChannel.toObject = function(includeInstance, msg) {
  var f, obj = {
    dsuidList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    channel: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    mode: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    area: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    group: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    zoneId: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    channelid: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel}
 */
proto.vdcapi.vdsm_NotificationDimChannel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vdcapi.vdsm_NotificationDimChannel;
  return proto.vdcapi.vdsm_NotificationDimChannel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vdcapi.vdsm_NotificationDimChannel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel}
 */
proto.vdcapi.vdsm_NotificationDimChannel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addDsuid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChannel(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMode(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setArea(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGroup(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setZoneId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setChannelid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vdcapi.vdsm_NotificationDimChannel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vdcapi.vdsm_NotificationDimChannel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vdcapi.vdsm_NotificationDimChannel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDsuidList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * repeated string dSUID = 1;
 * @return {!Array<string>}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.getDsuidList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.setDsuidList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.addDsuid = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.clearDsuidList = function() {
  return this.setDsuidList([]);
};


/**
 * optional int32 channel = 2;
 * @return {number}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.getChannel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.setChannel = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.clearChannel = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.hasChannel = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 mode = 3;
 * @return {number}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.getMode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.setMode = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.clearMode = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.hasMode = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 area = 4;
 * @return {number}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.getArea = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.setArea = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.clearArea = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.hasArea = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 group = 5;
 * @return {number}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.getGroup = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.setGroup = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.clearGroup = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.hasGroup = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int32 zone_id = 6;
 * @return {number}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.getZoneId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.setZoneId = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.clearZoneId = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.hasZoneId = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string channelId = 7;
 * @return {string}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.getChannelid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.setChannelid = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.vdcapi.vdsm_NotificationDimChannel} returns this
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.clearChannelid = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.vdcapi.vdsm_NotificationDimChannel.prototype.hasChannelid = function() {
  return jspb.Message.getField(this, 7) != null;
};


